<a href="https://colab.research.google.com/github/imamslogic/NLP/blob/main/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word Embedding

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

# One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[2105, 8552, 2089, 8967], [2105, 8552, 2089, 8523], [2105, 6413, 2089, 98], [8401, 6282, 8832, 4153, 5258], [8401, 6282, 8832, 4153, 6172], [7025, 2105, 793, 2089, 132], [6985, 246, 4181, 4153]]


# Word Embedding model

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2105 8552 2089 8967]
 [   0    0    0    0 2105 8552 2089 8523]
 [   0    0    0    0 2105 6413 2089   98]
 [   0    0    0 8401 6282 8832 4153 5258]
 [   0    0    0 8401 6282 8832 4153 6172]
 [   0    0    0 7025 2105  793 2089  132]
 [   0    0    0    0 6985  246 4181 4153]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[-1.72207467e-02  3.27073410e-03  4.23947461e-02 -1.65056363e-02
    3.20271514e-02 -4.72275279e-02 -4.00794521e-02 -3.31542715e-02
   -4.89753969e-02 -1.65914185e-02]
  [-1.72207467e-02  3.27073410e-03  4.23947461e-02 -1.65056363e-02
    3.20271514e-02 -4.72275279e-02 -4.00794521e-02 -3.31542715e-02
   -4.89753969e-02 -1.65914185e-02]
  [-1.72207467e-02  3.27073410e-03  4.23947461e-02 -1.65056363e-02
    3.20271514e-02 -4.72275279e-02 -4.00794521e-02 -3.31542715e-02
   -4.89753969e-02 -1.65914185e-02]
  [-1.72207467e-02  3.27073410e-03  4.23947461e-02 -1.65056363e-02
    3.20271514e-02 -4.72275279e-02 -4.00794521e-02 -3.31542715e-02
   -4.89753969e-02 -1.65914185e-02]
  [-6.62870333e-03  5.65793365e-03 -8.87753814e-03 -2.55118143e-02
   -1.21921301e-02  2.42798217e-02  3.45192887e-02  1.63769722e-03
    1.58704035e-02 -4.50748801e-02]
  [-2.77472492e-02  1.60561912e-02  4.51279543e-02  2.77389549e-02
   -4.52110432e-02  1.96285136e-02 -1.34417787e-02  4.93495576e-02
   -3.20701152e-

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 2105, 8552, 2089, 8967], dtype=int32)

In [14]:
print(model.predict(embedded_docs)[0])

[[-0.01722075  0.00327073  0.04239475 -0.01650564  0.03202715 -0.04722753
  -0.04007945 -0.03315427 -0.0489754  -0.01659142]
 [-0.01722075  0.00327073  0.04239475 -0.01650564  0.03202715 -0.04722753
  -0.04007945 -0.03315427 -0.0489754  -0.01659142]
 [-0.01722075  0.00327073  0.04239475 -0.01650564  0.03202715 -0.04722753
  -0.04007945 -0.03315427 -0.0489754  -0.01659142]
 [-0.01722075  0.00327073  0.04239475 -0.01650564  0.03202715 -0.04722753
  -0.04007945 -0.03315427 -0.0489754  -0.01659142]
 [-0.0066287   0.00565793 -0.00887754 -0.02551181 -0.01219213  0.02427982
   0.03451929  0.0016377   0.0158704  -0.04507488]
 [-0.02774725  0.01605619  0.04512795  0.02773895 -0.04521104  0.01962851
  -0.01344178  0.04934956 -0.03207012 -0.00092464]
 [-0.03995044  0.00218234  0.02836205  0.02678652 -0.04418074 -0.03524728
  -0.03488506 -0.02197673  0.01725915 -0.02328819]
 [ 0.01761929  0.0420589  -0.02473624 -0.01625118 -0.03959858 -0.0259633
   0.01349342  0.00838552  0.01731649 -0.02600474]]
